### ISSUE TITLE
Images on Safari Browser 8.0 - orientation problem

### ISSUE THREAD

**Issue by ouya99** [rikonor/meteor-autoform-image-gallery#4]
On Safari:

The images in the category list are added from top to buttom (one column for the first images)... whereas on Chrome it does look fine (one row - added from left to right)

**Comment by rikonor** [comment]
Which version of Safari are you using? I'd like to try and reproduce this - I have Safari 9 installed and it looks fine. I think it might be a flexbox issue.

**Comment by rikonor** [comment]
Should be fixed in https://github.com/rikonor/meteor-autoform-image-gallery/commit/cdcc1c330b43eb68306cb364db0a7c7cf843913d.
Thank you for your great feedback.

**Comment by rikonor** [comment]
@java99 Could you let me know if this was fixed for you and if so close the issue?

Thanks

**Comment by ouya99** [comment]
Thanks a lot. Has been fixed for Safari 8.0.
